<html>

<body>

<h1>Mamilla's restraunt</h1>
<p>The first restaurant proprietor is believed to have been one A. Boulanger, a soup vendor, who opened his business in Paris in 1765.</p>

<h2>Veg items</h2>
<pre>
Gobi
Paneer
veg biriyani
</pre>

<h3>Non-Veg items</h3>
<pre>
Chicken Lolipop
Salmon fish
Chicken biriyani
</pre>


</body>
</html>
